server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/word_learning?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis 配置
  data:
    redis:
      database: 10
      password: 123456
      port: 6379
      host: localhost

mybatis-plus:
  # 如果你还有 XML 文件就放开下面这行
  # mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qinyuan.wordlearning.entity
  configuration:
    # 驼峰转下划线（数据库 user_name → Java userName），默认就是 true
    map-underscore-to-camel-case: true
    # 打印 SQL（开发时建议打开，能看到 MyBatis-Plus 自动生成的 SQL）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键自增策略
      id-type: auto
jwt:
  secret: word-memorize-secret-key-2025-long-enough-key
  expire: 7*24*60*60